services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "brainag"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5433:5432"