services:
  web:
    build: .
    network_mode: bridge
    env_file:
      - .env
    ports:
      - "4050:4050"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "brainag"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql